apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: github-api
  template:
    metadata:
      labels:
        app: github-api
    spec:
      containers:
      - name: github-api
        image: ghcr.io/rsbguerra/github-api:latest
        ports:
        - containerPort: 8080
